#!/bin/bash
set -x
if [ -z "$4" ]; then
  echo "Usage: $(basename $0) model seed psi outfile"
  exit 1
fi

set -e

cd $(dirname $0)

# python 3.6 + older Tensorflow required
. env/bin/activate

# for nvcc
export PATH=$PATH:/usr/local/cuda-11.6/bin/

./make_a_face.py --model=$1 --seed=$2 --psi=$3 --out=$4
